org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# NeoForge Properties
minecraft_version=1.21.1
neo_version=21.1.125
neo_version_range=[21.1,)
loader_version_range=[4,)
mapping_channel=official
mapping_version=1.21.1

# Mod Properties
mod_version=1.0.2
maven_group=com.tatuto.fixflashback
archives_base_name=fix_flashback

mod_id=fix_flashback
mod_name=Fix Flashback
mod_license=MIT
mod_authors=tatuto-riku

mod_description=Fixes the NoClassDefFoundError crash caused by Flashback running on NeoForge via Sinytra Connector
